updates:
  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "daily"

    labels:
      - dependencies
      - docker

    commit-message:
      prefix: "docker"

    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "development"
    schedule:
      interval: "weekly"

    labels:
      - dependencies
      - github-actions

    commit-message:
      prefix: "github-actions"

    open-pull-requests-limit: 5
