name: Merge branch with label - "auto-merge"
on:
  push:
    branches: [ "development" ]
  pull_request:
    types: [labeled]
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3

      - name: Merge by labeled
        uses: devmasx/merge-branch@v1.4.0
        with:
          label_name: 'auto-merge'
          target_branch: 'development'
          github_token: ${{ secrets.GITHUB_TOKEN }}
