name: Merge branch with label - "auto-merge"
on:
 workflow_dispatch:
 pull_request:
   branches: [ "master" ]
   types: [labeled]
 pull_request_review:
   types:
     - submitted
 check_suite:
   types:
     - completed
 status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout repository
         uses: actions/checkout@v4.2.2
         id: auto-merge
      -  name: auto-merge
         uses: "pascalgn/automerge-action@v0.15.6"
         env:
           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
           MERGE_LABELS: "auto-merge"